sudo: required
services:
  - docker

before_install:
  - docker build -t rimmigill/docker-and-react1 -f Dockerfile .

script:
  - docker run -e CI=true  rimmigill/docker-and-react1 npm run test

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-and-react"
  env: "DockerAndReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-815585712149"
  bucket_path: "docker-and-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
