sudo: required
services:
  - docker

before_install:
  - docker build -t rimmigill/docker-and-react -f Dockerfile.dev .

script:
  - docker run -e CI=true  rimmigill/docker-react-test2 npm run test

language: generic